[keyboard]
name = "rmk-config-unibox"
product_name = "rmk-config-unibox"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "bhe"
chip = "rp2040"

[matrix]
# Input and output pins are mandatory
matrix_type = "direct_pin"
direct_pin_low_active = true
direct_pins = [
[ "PIN_14","PIN_18", "PIN_19", "PIN_20", "PIN_16", "PIN_17" ],
[ "PIN_5" ,"PIN_3" , "PIN_4" , "PIN_2" , "_",      "_" ],
[ "PIN_10","PIN_11", "PIN_12", "PIN_13", "_", "_" ],
[ "PIN_6","PIN_7", "PIN_8", "PIN_9", "_", "_" ],
]

# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[behavior.combo]
timeout = "150ms"
combos = []
[layout]
rows = 4
cols = 6
layers = 3
keymap = [
    [
        ["MO(1)", "Kc2", "Kc3", "Kc4", "DF(1)", "Bootloader"],
        ["MT(A, LCtrl)", "MT(S, LGui)", "MT(D, LShift)", "W", "_", "_"],
        ["U", "I", "O", "P", "_", "_"],
        ["H", "J", "K", "L", "_", "_"],
    ],
    [
        ["Esc", "Enter", "Kc3", "Kc4", "DF(2)", "Kc6"],
        ["A", "S", "D", "W", "_", "_"],
        ["U", "I", "O", "P", "_", "_"],
        ["H", "J", "K", "L", "_", "_"],
    ],
    [
        ["Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6"],
        ["A", "S", "D", "W", "_", "_"],
        ["U", "I", "O", "P", "_", "_"],
        ["H", "J", "K", "L", "_", "_"],
    ],
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true


[storage]
# Storage feature is enabled by default
enabled = true

[behavior]
# Enable HRM
tap_hold = { enable_hrm = true, prior_idle_time = "70ms", hold_timeout = "250ms", post_wait_time = "0ms"}


